In [1]:
import numpy as np

In [6]:
array1=np.array([1,2,3,4,5,6,7])
array2=np.array([8,9,10,11,12,13,14])

In [7]:
print(array1+array2)

[ 9 11 13 15 17 19 21]


In [8]:
print(array2-array1)

[7 7 7 7 7 7 7]


In [9]:
print(array1*array2)

[ 8 18 30 44 60 78 98]


In [10]:
print(array2/array1)

[8.         4.5        3.33333333 2.75       2.4        2.16666667
 2.        ]


In [11]:
mean=np.mean(array1)
print(mean)

4.0


In [12]:
print(np.sum(array1))

28


In [14]:
print(np.max(array1))
print(np.min(array1))

7
1


In [15]:
print(array1>6)

[False False False False False False  True]


In [16]:
print(array1+3)

[ 4  5  6  7  8  9 10]
