In [1]:
import numpy as np

In [2]:
array1=np.array([10,20,30,40,50])
print(array1[1])


20


In [3]:
print(array1[-2])

40


In [4]:
print(array1[1:4])

[20 30 40]


In [5]:
print(array1[::2])

[10 30 50]


In [7]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1,1])

5


In [11]:
print('Second Row: ',matrix[1,:])

Second Row:  [4 5 6]


In [12]:
print('Second Column: ',matrix[:,1])

Second Column:  [2 5 8]


In [14]:
data=np.array([1,2,3,np.nan,4,5])
print(np.isnan(data))

[False False False  True False False]


In [16]:
data_fill=np.nan_to_num(data,nan=200)
print(data_fill)

[  1.   2.   3. 200.   4.   5.]
