In [14]:
import numpy as np
array1=np.array(([1,2],[3,4]))
array2=np.array(([5,6],[7,8]))
mult=np.dot(array1,array2)
print(mult)

[[19 22]
 [43 50]]


In [4]:
inv=np.linalg.inv(array1)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
eval, evect=np.linalg.eig(array1)
print(eval)
print(evect)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [6]:
data=np.array([1,2,3,4,5,6,7])
print(np.mean(data))
print(np.std(array1))

4.0
1.118033988749895


In [8]:
data2=np.array([11,12,13,14,15,16,17])
cor=np.corrcoef(data,data2)
print(cor)

[[1. 1.]
 [1. 1.]]


In [9]:
np.savetxt('outputmatrix.csv',mult,delimiter=',')

In [10]:
np.save('output.npy',mult)
new_matrix=np.load('output.npy')
print(new_matrix)

[[19 22]
 [43 50]]


In [15]:
import pandas as pd


In [17]:
df=pd.DataFrame(mult)


In [19]:
df.to_excel('outputexcel1.xlsx')